#!/bin/bash
apt -y install nano zip python cowsay python2 wget php git zsh openssh curl
pip2 install beautifulsoup4
pip2 install termcolor
pip2 install argparse
pip2 install request
pip2 install pysocks
pkg install mpv
pkg install libcurl
pip install mps_youtube
pip install youtube_dl
